// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYtVdbEmSFNxUt51SVmuGeAiygINRKXy4',
    appId: '1:3747640211:web:8544500933cf4f41086e66',
    messagingSenderId: '3747640211',
    projectId: 'portfolio-d5ba6',
    authDomain: 'portfolio-d5ba6.firebaseapp.com',
    storageBucket: 'portfolio-d5ba6.appspot.com',
    measurementId: 'G-XVKF0NYJCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsiLA6TEXyQS-tKCfmkv--pJ4FfVarttM',
    appId: '1:3747640211:android:135ae5a5118702e0086e66',
    messagingSenderId: '3747640211',
    projectId: 'portfolio-d5ba6',
    storageBucket: 'portfolio-d5ba6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADGosaQi0LoXnAqxOGjQdIDlj8dydZQNs',
    appId: '1:3747640211:ios:5af678869791c60d086e66',
    messagingSenderId: '3747640211',
    projectId: 'portfolio-d5ba6',
    storageBucket: 'portfolio-d5ba6.appspot.com',
    iosClientId: '3747640211-r6aj7h4coh5dfdibs0n9o57q6a4mbmsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );
}
